### ISSUE TITLE
Activation function used

### ISSUE THREAD

**Issue by MorganREN** [wukekever/landscapes#1]
Hello! 
Could you please explain why you used `x * torch.sigmoid(x)` for the activation function instead of just `torch.sigmoid(x)`?
Thank you.

**Comment by wukekever** [comment]
Hi！You can try other activation function, but the conclusion may be    different.

**Comment by MorganREN** [comment]
> Hi！You can try other activation function, but the conclusion may be different.

Ok. Thank you.
